//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gabay_Final_V2.Views.DashBoard.Admin_Homepage
{


    public partial class WebForm1
    {

        /// <summary>
        /// lblDept_name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDept_name;

        /// <summary>
        /// StudentuserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label StudentuserCountLabel;

        /// <summary>
        /// DepatmentuserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DepatmentuserCountLabel;

        /// <summary>
        /// StudentApprovedUserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label StudentApprovedUserCountLabel;

        /// <summary>
        /// StudentPendingUserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label StudentPendingUserCountLabel;

        /// <summary>
        /// BarStudentsUserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsUserCountLabel;

        /// <summary>
        /// BarStudentsCCSUserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsCCSUserCountLabel;

        /// <summary>
        /// BarStudentsNursingUserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsNursingUserCountLabel;

        /// <summary>
        /// BarStudentsCriminologyUserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsCriminologyUserCountLabel;

        /// <summary>
        /// BarStudentsTourismHospitalityCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsTourismHospitalityCountLabel;

        /// <summary>
        /// BarStudentsBusinessAdministrationandAccountancyUserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsBusinessAdministrationandAccountancyUserCountLabel;

        /// <summary>
        /// BarStudentsCustomsAdministrationUserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsCustomsAdministrationUserCountLabel;

        /// <summary>
        /// BarStudentsMarineTransportationCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsMarineTransportationCountLabel;

        /// <summary>
        /// BarStudentsMarineEngineeringCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsMarineEngineeringCountLabel;

        /// <summary>
        /// BarStudentsElectronicsandCommunicationEngineeringUserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsElectronicsandCommunicationEngineeringUserCountLabel;

        /// <summary>
        /// BarStudentsElectricalEngineeringUserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsElectricalEngineeringUserCountLabel;

        /// <summary>
        /// BarStudentsMechanicalEngineeringnUserCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsMechanicalEngineeringnUserCountLabel;

        /// <summary>
        /// BarStudentsIndustrialEngineeringCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsIndustrialEngineeringCountLabel;

        /// <summary>
        /// BarStudentsComputerEngineeringCountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField BarStudentsComputerEngineeringCountLabel;
    }
}
